name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: |
          mkdir -p dist
          cp -r manuais dist/
          [ -d assets ] && cp -r assets dist/ || true
          
          if [ ! -f dist/index.html ]; then
            cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>EleveLab - Manuais</title>
              <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body {
                      font-family: -apple-system, sans-serif;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                  }
                  .container {
                      background: white;
                      border-radius: 20px;
                      padding: 40px;
                      max-width: 800px;
                      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                  }
                  h1 { color: #E73700; margin-bottom: 30px; }
                  .manual-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 20px;
                  }
                  .manual-card {
                      background: #f8f9fa;
                      border-radius: 10px;
                      padding: 20px;
                      text-decoration: none;
                      color: #333;
                      transition: all 0.3s;
                  }
                  .manual-card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 10px 30px rgba(231,55,0,0.2);
                  }
                  .manual-card h3 { color: #E73700; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>EleveLab - Manuais Interativos</h1>
                  <div class="manual-grid">
                      <a href="manuais/SOX406/" class="manual-card">
                          <h3>SOX406</h3>
                          <p>Determinador de Gordura</p>
                      </a>
                      <a href="manuais/analisador-fibras/" class="manual-card">
                          <h3>Analisador de Fibras</h3>
                          <p>Sistema automatizado</p>
                      </a>
                      <a href="manuais/destilador-nitrogenio/" class="manual-card">
                          <h3>Destilador de Nitrogênio</h3>
                          <p>Equipamento de destilação</p>
                      </a>
                      <a href="manuais/biorreator/" class="manual-card">
                          <h3>Biorreator</h3>
                          <p>Sistema de cultivo</p>
                      </a>
                      <a href="manuais/fotobiorreator/" class="manual-card">
                          <h3>Fotobiorreator</h3>
                          <p>Reator com iluminação</p>
                      </a>
                      <a href="manuais/nobreak-duo-pro/" class="manual-card">
                          <h3>Nobreak Duo Pro</h3>
                          <p>Sistema UPS</p>
                      </a>
                  </div>
              </div>
          </body>
          </html>
          EOF
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4