name: Deploy to GitHub Pages - Fixed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true  # IMPORTANTE: Para arquivos grandes
        
      - name: Debug - List images before build
        run: |
          echo "=== Verificando imagens no repositório ==="
          find manuais -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | head -20
          echo "=== Total de imagens ==="
          find manuais -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | wc -l
          
      - name: Build
        run: |
          # Criar diretório dist
          mkdir -p dist
          
          # Copiar TUDO de manuais preservando estrutura
          cp -r manuais dist/
          
          # Copiar assets se existir
          [ -d assets ] && cp -r assets dist/ || true
          
          # Criar .nojekyll para evitar processamento Jekyll
          touch dist/.nojekyll
          
          # Verificar se as imagens foram copiadas
          echo "=== Verificando imagens após cópia ==="
          find dist/manuais -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | head -20
          echo "=== Total de imagens copiadas ==="
          find dist/manuais -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | wc -l
          
          # Verificar tamanho das imagens
          echo "=== Tamanho das imagens ==="
          ls -lh dist/manuais/SOX406/images/interface/interface-*.jpg || echo "Imagens não encontradas!"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4