name: Deploy to GitHub Pages

on:
  # Executa em push para a branch main
  push:
    branches: [ main ]
  # Permite executar manualmente pela interface do GitHub
  workflow_dispatch:

# Permissões necessárias para o GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: |
          # Criar estrutura de build para GitHub Pages
          mkdir -p dist
          
          # Copiar manuais
          cp -r manuais dist/
          
          # Copiar assets se existirem
          [ -d assets ] && cp -r assets dist/ || true
          
          # Criar index.html principal se não existir
          if [ ! -f dist/index.html ]; then
            cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="pt-BR">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>EleveLab - Manuais de Equipamentos</title>
              <style>
                  * { margin: 0; padding: 0; box-sizing: border-box; }
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      min-height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      padding: 20px;
                  }
                  .container {
                      background: white;
                      border-radius: 20px;
                      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                      padding: 40px;
                      max-width: 800px;
                      width: 100%;
                  }
                  h1 {
                      color: #E73700;
                      margin-bottom: 10px;
                      font-size: 2.5em;
                  }
                  .subtitle {
                      color: #666;
                      margin-bottom: 30px;
                      font-size: 1.1em;
                  }
                  .manual-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 20px;
                      margin-top: 30px;
                  }
                  .manual-card {
                      background: #f8f9fa;
                      border-radius: 10px;
                      padding: 20px;
                      text-decoration: none;
                      color: #333;
                      transition: all 0.3s ease;
                      border: 2px solid transparent;
                  }
                  .manual-card:hover {
                      transform: translateY(-5px);
                      box-shadow: 0 10px 30px rgba(231, 55, 0, 0.2);
                      border-color: #E73700;
                  }
                  .manual-card h3 {
                      color: #E73700;
                      margin-bottom: 10px;
                  }
                  .manual-card p {
                      color: #666;
                      font-size: 0.9em;
                  }
                  .status {
                      display: inline-block;
                      padding: 4px 8px;
                      border-radius: 4px;
                      font-size: 0.8em;
                      font-weight: bold;
                      margin-top: 10px;
                  }
                  .status.active { background: #4CAF50; color: white; }
                  .status.beta { background: #FF9800; color: white; }
                  .footer {
                      text-align: center;
                      margin-top: 40px;
                      padding-top: 20px;
                      border-top: 1px solid #e0e0e0;
                      color: #666;
                      font-size: 0.9em;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>EleveLab</h1>
                  <p class="subtitle">Manuais Interativos de Equipamentos Científicos</p>
                  
                  <div class="manual-grid">
                      <a href="manuais/SOX406/" class="manual-card">
                          <h3>SOX406</h3>
                          <p>Determinador de Gordura - Método Goldfish</p>
                          <span class="status active">ATIVO</span>
                      </a>
                      
                      <a href="manuais/analisador-fibras/" class="manual-card">
                          <h3>Analisador de Fibras</h3>
                          <p>Sistema automatizado para análise de fibras</p>
                          <span class="status active">ATIVO</span>
                      </a>
                      
                      <a href="manuais/destilador-nitrogenio/" class="manual-card">
                          <h3>Destilador de Nitrogênio</h3>
                          <p>Equipamento para destilação e análise</p>
                          <span class="status active">ATIVO</span>
                      </a>
                      
                      <a href="manuais/biorreator/" class="manual-card">
                          <h3>Biorreator</h3>
                          <p>Sistema de cultivo celular controlado</p>
                          <span class="status active">ATIVO</span>
                      </a>
                      
                      <a href="manuais/fotobiorreator/" class="manual-card">
                          <h3>Fotobiorreator</h3>
                          <p>Reator para cultivo com iluminação</p>
                          <span class="status active">ATIVO</span>
                      </a>
                      
                      <a href="manuais/nobreak-duo-pro/" class="manual-card">
                          <h3>Nobreak Duo Pro</h3>
                          <p>Sistema de energia ininterrupta</p>
                          <span class="status active">ATIVO</span>
                      </a>
                  </div>
                  
                  <div class="footer">
                      <p>© 2025 EleveLab - Equipamentos Científicos</p>
                      <p>Atualizado automaticamente via GitHub Actions</p>
                  </div>
              </div>
          </body>
          </html>
          EOF
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Job de Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4